### ISSUE TITLE
Opening clojure REPL fails / Fix PATH problems 

### ISSUE THREAD

**Issue by sandover** [wuub/SublimeREPL#11]
I keep seeing "[Errno 2] No such file or directory" failures when I try to open the Clojure REPL.  Mac OS 10.7.  

I'm guessing it's failing to find leiningen.  However, lein is definitely on my PATH, at /usr/local/bin/lein .  Does Sublime Text have a different set of PATHs than the ones I have in a bash shell?

**Comment by jefffriesen** [comment]
Adding the absolute path to `lein` worked for me inside Preferences/Package Settings/SublimeREPL/Settings - User:
```
{
  "default_extend_env":
  {
    "PATH": "/Users/username/bin:{PATH}:/usr/local/bin"
  }
}
```
But a relative path did not work:
```
"PATH": "~/bin:{PATH}:/usr/local/bin"
```
