### ISSUE TITLE
Recognize `knitr` syntax as `R`

### ISSUE THREAD

**Issue by wngrtn** [wuub/SublimeREPL#165]
I use the `KnitrSublime` package to edit `knitr` documents. It would be great to be able to  send code from documents with this syntax to an R REPL. Currently I have to switch to `R` syntax to send the code, but that (of course) messes up the syntax highlighting.

Any hints as to how I could fix that myself?

**Comment by fredcallaway** [comment]
If anyone else is having similar problems, the general solution is to add `additional_scopes": ["SOURCE"]` where SOURCE is your unsupported syntax. E.g. if you get the error message: "No REPL found for 'html.markdown.rmarkdown'",  you would add: `additional_scopes": ["html.markdown.rmarkdown"]`

**Comment by bnicenboim** [comment]
I see this is closed, but what happens if there's need for more than 1 additional scope, I tried this:
"additional_scopes":["tex.latex.knitr.beamer.ing","tex.latex.knitr.ing"]
but it didn't work

**Comment by mereldawu** [comment]
I also want to add an additional scope: "additional_scopes": ["html.markdown.rmarkdown","tex.latex.knitr.ing"] 
But it also doesn't work?
