### ISSUE TITLE
[CR] showing up at IPython line endings in Windows Sublime Text 3

### ISSUE THREAD

**Issue by MattDMo** [wuub/SublimeREPL#166]
![ipython](https://f.cloud.github.com/assets/1776358/489575/f338e7c2-b99f-11e2-946b-92f3cdd7e6d2.jpg)
I'm using build 3033 (just downloaded a few hours ago), and I just cloned the `master` branch of the SublimeREPL repository, so everything is up to date. Is this something that can be fixed in my `ipython_config.py` or something on your end? ST2's IPython works fine, it's just ST3...

**Comment by matiasmorant** [comment]
probably this is the same issue that makes python's Tqdm module unusable with sublimerepl
