### ISSUE TITLE
"Evaluate in REPL" doesn't appear to have any effect in Clojure/Python REPLs

### ISSUE THREAD

**Issue by IrwinKwan** [wuub/SublimeREPL#183]
Using "Evaulate in REPL" in either a Clojure REPL or a Python REPL doesn't appear to have any effect.

The key log appears to trigger the event and the keyboard commands I use should be correct:

`key evt: control+,
chr evt: l (0x6c)`

However, no output appears on the REPL side.

Typing in the REPL normally works fine.

I am probably doing something wrong, or my setup is incorrect - are there further troubleshooting tips I can take?

**Comment by belun** [comment]
for me, the suggested solution did not work. however i installed EnhancedClojure package in Sublime3 and now it is fine
