### ISSUE TITLE
repl_transfer_current doesn't work first time; must execute twice

### ISSUE THREAD

**Issue by rogerjbos** [wuub/SublimeREPL#261]
I have configured SublimeREPL to work with both R and Julia (using SublimeJulia) using the ctrl+enter sequence to evaluation a section of text, but I get no response the first time I hit ctrl+enter.  If I do it twice quickly then it works.  Any idea why this might be?

Here are my Key Bindings - User settings:

[
// Characters that are considered to separate words – does not include periods.
// Place comma at the end of the line if there are multiple keybindings.
{"word_separators": "/\()\"‘-:,;~!@#$%^&*|+=[]{}`~?"},

// Modified Sublime-REPL keybindings for an "R-friendly" set of shortcuts.
// Copy and paste this text into the Key Bindings - User (under Preferences menu).
// For more information, see http://tomschenkjr.net/2012/05/17/using-sublime-text-2-for-r/

// Executes a selection of text in REPL, latter only displays code and does not execute
{ "keys": ["ctrl+enter"], "command": "repl_transfer_current", "args": {"scope": "selection"}},
{ "keys": ["ctrl+enter", "r"], "command": "repl_transfer_current", "args": {"scope": "selection", "action":"view_write"}},

// Executes the entire file (build) in REPL, latter only displays code and does not execute
{ "keys": ["ctrl + f7"], "command": "repl_transfer_current", "args": {"scope": "file"}},
{ "keys": ["ctrl + f7", "r"], "command": "repl_transfer_current", "args": {"scope": "file", "action":"view_write"}},

// Executes line(s) of text in REPL terminal, latter only displays code and does not execute
{ "keys": ["ctrl+alt+enter"], "command": "repl_transfer_current", "args": {"scope": "lines"}},
{ "keys": ["ctrl+alt+enter", "r"], "command": "repl_transfer_current", "args": {"scope": "lines", "action":"view_write"}},

// Executes a block (e.g., a custom function) of text in REPL terminal, latter only displays code and does not execute
{ "keys": ["ctrl+shift+alt+enter"], "command": "repl_transfer_current", "args": {"scope": "block"}},
{ "keys": ["ctrl+shift+alt+enter", "r"], "command": "repl_transfer_current", "args": {"scope": "block", "action":"view_write"}}
]

**Comment by jeremymiles** [comment]
@rogerjbos  - would you mind saying how you changed  ["ctrl+enter", r] (if you remember). I'm having the same problem.
