### ISSUE TITLE
How to set python 3 in SublimeREPL?

### ISSUE THREAD

**Issue by ivadenis** [wuub/SublimeREPL#264]
Hi, I'm on mac and looking to use SublimeREPL with python 3.3 version there.
Right now I have 2.7.

My os version is 10.8

Thanks!

**Comment by harri00413** [comment]
Thanks very much for your help. Trying this on OS X El Capitan with Sublime Text 3 and Python 3.5. I presume the Path is /Library/Frameworks/Python.framework/Versions/3.5/bin. I replace the 
"cmd": ["/opt/local/bin/python3", "-i", "-u"],
with 
"cmd": ["//Library/Frameworks/Python.framework/Versions/3.5/bin", "-i", "-u"]
then error:
PermissionError(13, 'Permission denied')
should I chmod anything? Or should I have sudo'd something I haven't?

**Comment by MattDMo** [comment]
@harri00413 you forgot to add the `python3` executable on to the end of it:

    "cmd": ["//Library/Frameworks/Python.framework/Versions/3.5/bin/python3", "-i", "-u"]

**Comment by harri00413** [comment]
Thanks, that worked. Now I only need to make a quick link or so to run the current module.

**Comment by Xwoder** [comment]
@MattDMo 

Thanks a lot, I try it, easy to use.

**Comment by yanghanyugithub** [comment]
if you have installed python3 on your mac, just replace "cmd": ["python", "-i", "-u"], with "cmd": ["python3", "-i", "-u"],

**Comment by YuchenS1** [comment]
if you have installed python3 and SublimeREPL, you can try setting up key bindings with the correct path to the python3 file.

```
[
     {
        "keys":["super+ctrl+r"],
        "command": "repl_open",
                     "caption": "Python 3.6 - Open File",
                     "id": "repl_python",
                     "mnemonic": "p",
                     "args": {
                        "type": "subprocess",
                        "encoding": "utf8",
                        "cmd": ["The directory to your python3.6 file", "-i", "$file"],
                        "cwd": "$file_path",
                        "syntax": "Packages/Python/Python.tmLanguage",
                        "external_id": "python",
                        "extend_env": {"PYTHONIOENCODING": "utf-8"}
                        }
    }
]
```

You can try by copying this code into your /Sublime Text 3/Preferences/Key Bindings/

Hope this helps!

**Comment by ArmCM** [comment]
Hi, check this

https://coderwall.com/p/nhq2gg/setting-up-sublimerepl-with-python3

**Comment by JayRizzo** [comment]
> If you don't want to use `virtualenv`, create `Packages/User/SublimeREPL/config/Python/Main.sublime-menu` with the following contents:
> ...
> You'll need to modify the path to `python3` if you're not using MacPorts. I'm of two minds about virtualenvs - on the one hand they're great for creating perfectly customized environments, testing different versions of modules, etc., but on the other hand I like just having one single environment with all of my packages available. The choice is up to you :)

Thank you for this @MattDMo, I had to modify mine a bit differently for my mac. 

1. Open `Terminal.app`
2. Type:  `subl "~/Library/Application Support/Sublime Text 3/Packages/SublimeREPL/config/Python/Main.sublime-menu"` 
3. To open file in Sublime (* if you have that configured)
4. I had set my config to be the following that seems to be working for me.  Hope this helps someone else. 😄 .

```json
[
    {
        "id": "tools",
        "children":
        [{
            "caption": "SublimeREPL",
            "mnemonic": "R",
            "id": "SublimeREPL",
            "children":
            [
                {"caption": "Python 3",
                    "id": "Python3",
                    "children":[
                        {"command": "repl_open",
                         "caption": "Python 3",
                         "id": "repl_python3",
                         "mnemonic": "p",
                         "args": {
                            "type": "subprocess",
                            "encoding": "utf8",
                            "cmd": ["/Library/Frameworks/Python.framework/Versions/3.9/bin/python3", "-i", "-u"],
                            "cwd": "$file_path",
                            "syntax": "Packages/Python/Python.tmLanguage",
                            "external_id": "python",
                            "extend_env": {"PYTHONIOENCODING": "utf-8"}
                        }
                    },
                    {"command": "repl_open",
                     "caption": "Python 3 - IPython",
                     "id": "repl_python_ipython3",
                     "mnemonic": "p",
                     "args": {
                        "type": "subprocess",
                        "encoding": "utf8",
                        "autocomplete_server": "true",
                        "cmd": {
                            "osx": ["/Library/Frameworks/Python.framework/Versions/3.9/bin/ipython3"]
                        },
                        "cwd": "$file_path",
                        "syntax": "Packages/Python/Python.tmLanguage",
                        "external_id": "python",
                        "extend_env": {
                            "PYTHONIOENCODING": "utf-8",
                            "SUBLIMEREPL_EDITOR": "$editor"
                        }
                    }
                },
                {"command": "repl_open",
                    "caption": "Python 3 - PDB current file",
                    "id": "repl_python_pdb",
                    "mnemonic": "D",
                    "args": {
                        "type": "subprocess",
                        "encoding": "utf8",
                        "cmd": ["/Library/Frameworks/Python.framework/Versions/3.9/bin/python3", "-i", "-u", "-m", "pdb", "$file_basename"],
                        "cwd": "$file_path",
                        "syntax": "Packages/Python/Python.tmLanguage",
                        "external_id": "python",
                        "extend_env": {"PYTHONIOENCODING": "utf-8"}
                    }
                },
                {"command": "repl_open",
                    "caption": "Python 3 - RUN current file",
                    "id": "repl_python3_run",
                    "mnemonic": "R",
                    "args": {
                        "type": "subprocess",
                        "encoding": "utf8",
                        "cmd": ["/Library/Frameworks/Python.framework/Versions/3.9/bin/python3", "-u", "$file_basename"],
                        "cwd": "$file_path",
                        "syntax": "Packages/Python/Python.tmLanguage",
                        "external_id": "python",
                        "extend_env": {"PYTHONIOENCODING": "utf-8"}
                        }
                    },
                ]}
            ]
        }]
    }
]

```
I had to remove this from iPython as it was complaining.
//, "-u", "${packages}/SublimeREPL/config/Python/ipy_repl.py" removed
<img width="359" alt="screenshot 2022-06-17 at 124357" src="https://user-images.githubusercontent.com/22861678/174354626-b30448b9-8a54-4b27-9276-c60f991e6b3b.png">

under Tools -> SublimeREPL looks like this now.
![screenshot 2022-06-17 at 131044](https://user-images.githubusercontent.com/22861678/174354746-2c81cd31-d539-480c-8776-4a87ad540e27.png)

"Don't Have A Good Day,
Have A Great Day!"
