### ISSUE TITLE
history for commands which sent to REPL

### ISSUE THREAD

**Issue by randy3k** [wuub/SublimeREPL#289]
currently, history for commands which evaluate in (not transferred to) REPL is not saved. 
is it your intention?

i think it would be reasonable to save  the evaluated  commands.

**Comment by ipstone** [comment]
Hello, I know this is a closed ticket, but my issue might be related: in the Sublime REPL R console, history() command will give the results: 

> > history()
> Error in file(con, "r") : cannot open the connection
> In addition: Warning message:
> In file(con, "r") :
>   cannot open file 'C:\Users\...\AppData\Local\Temp\RtmpcBKoO7\Rrawhist1e8c56fc4f27': No such file or directory


Might be the cause of this - because sublime REPL is not saving/writing history to this temp file?

Thanks in advance!

Isaac
