### ISSUE TITLE
Clojure REPL and escape characters in strings

### ISSUE THREAD

**Issue by DjebbZ** [wuub/SublimeREPL#291]
Hi,

First thanks for the plugin. Learning Clojure with it is a delightful experience.

I'm encountering a strange behaviour when I evaluate characters and regexps from my code. When I type `#{\a \b}` in the REPL, it returns itself normally. When I send this same code from my editor to the REPL, it fails with :

```
user=> (load-string "#{\a \b}")

RuntimeException Unsupported escape character: \a  clojure.lang.Util.runtimeException (Util.java:219)
RuntimeException Unmatched delimiter: }  clojure.lang.Util.runtimeException (Util.java:219)
RuntimeException EOF while reading string  clojure.lang.Util.runtimeException (Util.java:219)
```

So I have to double-escape every single characters, as well as special chars from regexps like so `#{\\a \\b}` so I can send them to the REPL from my code.

Is this behaviour normal ? To be expected ? A bug ? As I started to learn Clojure (my first Lisp ever) I may not know several things about how code and REPL differ. Any explanations very welcome.

**Comment by eeng** [comment]
Hi, this plugin has been of great help to me, so thank you very much!
Just one problem though, I'm experiencing this bug too. Is there a possibility that the fix has not been published yet on the Package Control?
