### ISSUE TITLE
node.js simply not working, at all

### ISSUE THREAD

**Issue by robmuh** [wuub/SublimeREPL#364]
No matter what I try, after 4 hours I can't get around this one. I've changed the paths and more.

net.js:605
    throw new TypeError('invalid data');

TypeError: invalid data
    at Socket.write (net.js:605:11)
    at REPLServer.Interface.prompt (readline.js:176:17)
    at REPLServer.displayPrompt (repl.js:397:8)
    at new REPLServer (repl.js:328:8)
    at Object.exports.start (repl.js:337:14)
    at C:\Users\MrRob\AppData\Roaming\Sublime Text 3\Packages\SublimeREPL\config\NodeJS\repl.js:5:20
    at Object.<anonymous> (C:\Users\MrRob\AppData\Roaming\Sublime Text 3\Packages\SublimeREPL\config\NodeJS\repl.js:38:3)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:349:32)

**_Repl Closed**_

```
```

**Comment by pascience** [comment]
Worked for me too, thanks :+1:

**Comment by iainwatt** [comment]
worked!

**Comment by vferko** [comment]
Changing to empty string '' worked as well

	var rep = repl.start({
	    prompt:    '', //null, 
	    source:    null, //process.stdin,
	    eval:      null, //require('vm').runInThisContext,
	    useGlobal: true, //false
	    useColors: false
	});

**Comment by butgit** [comment]
IT works like magic. Thanks.

**Comment by OliverJAsh** [comment]
This is still an issue, will it get fixed in master?

**Comment by Deepblue129** [comment]
Hey! It can be a little hard to find on the windows. Here is the path I found the config files @ C:\Users\micha\AppData\Roaming\Sublime Text 3\Packages\SublimeREPL\config\NodeJS

**Comment by goldnetonline** [comment]
A bottle of soda @teodoran, so saved my day.

**Comment by Demetrio92** [comment]
why on earth isn't this still a default setup? 2 years later the same error which is fixable by modifying a config file...

**Comment by ptolideh** [comment]
Wow...Super easy fix! thanks Rob

**Comment by kirin-yuen** [comment]
@teodoran it works, but how do you find this way to fix it? Modify the `repl.start` option one by one?

**Comment by liyachun01** [comment]
Thanks!

**Comment by ErAz7** [comment]
> I had the same problem, but managed to fix it by modifying the [path to Sublime Text]/Packages/SublimeREPL/config/NodeJS/repl.js config file.
> 
> On line 5 in the file there is a repl.start() call with a config object as an argument:
> 
> ```
> var rep = repl.start({
>     prompt:    null, //'> ',  
>     source:    null, //process.stdin,
>     eval:      null, //require('vm').runInThisContext,
>     useGlobal: true, //false
>     useColors: false
> });
> ```
> 
> @wuub has helpfully left in some comments with other possible config values, and for some strange reason, changing the "prompt" value to '>' fixed my problem. For easy copy/pasting, this was the code that worked for me:
> 
> ```
> var rep = repl.start({
>     prompt:    '> ', //null, 
>     source:    null, //process.stdin,
>     eval:      null, //require('vm').runInThisContext,
>     useGlobal: true, //false
>     useColors: false
> });
> ```

The reason might be the '>' character appears in stdout when you enter "node" in cmd, so when it is set to null, it won't be detected but when you change it to '>', it simply detects that process is waiting for input
This was the approach I used in nodeJS child processes to detect if child process is waiting for interaction from node process and perhaps is the case here

**Comment by mayank-bizbms** [comment]
> I had the same problem, but managed to fix it by modifying the [path to Sublime Text]/Packages/SublimeREPL/config/NodeJS/repl.js config file.
> 
> On line 5 in the file there is a repl.start() call with a config object as an argument:
> 
> ```
> var rep = repl.start({
>     prompt:    null, //'> ',  
>     source:    null, //process.stdin,
>     eval:      null, //require('vm').runInThisContext,
>     useGlobal: true, //false
>     useColors: false
> });
> ```
> 
> @wuub has helpfully left in some comments with other possible config values, and for some strange reason, changing the "prompt" value to '>' fixed my problem. For easy copy/pasting, this was the code that worked for me:
> 
> ```
> var rep = repl.start({
>     prompt:    '> ', //null, 
>     source:    null, //process.stdin,
>     eval:      null, //require('vm').runInThisContext,
>     useGlobal: true, //false
>     useColors: false
> });
> ```

Thanks...this worked for me :)
