### ISSUE TITLE
Trying to get Julia REPL happening

### ISSUE THREAD

**Issue by ZacCranko** [wuub/SublimeREPL#385]
Hi I wrote the following Main.sublime-menu for Julia but it doesn't seem to be working. Any advice?

```
[
     {
        "id": "tools",
        "children":
        [{
            "caption": "SublimeREPL",
            "mnemonic": "j",
            "id": "SublimeREPL",
            "children":
            [
                {"command": "repl_open",
                 "caption": "Julia",
                 "id": "repl_julia",
                 "mnemonic": "j",
                 "args": {
                    "type": "subprocess",
                    "encoding": "utf8",
                    "cmd": ["/Users/zaccranko/Applications/Julia.app/Contents/Resources/julia/bin/julia"],
                    "cwd": "$file_path",
                    "external_id": "julia"
                    }
                }
            ]
        }]
    }
]
```

**Comment by janxkoci** [comment]
Hi, I'd like to pick this up.

I managed to make the basic repl work, but it's not perfect - for start, it's missing a prompt, you just type on an empty line.

![Snímek z 2022-03-30 17-41-25](https://user-images.githubusercontent.com/19331850/160875674-eb896a78-a514-401a-a3ff-29da7fe4b198.png)


I made a copy of the Lua directory inside `Packages/SublimeREPL/config/` and modified them for Julia. Here are the files I use:

- `Main.sublime-menu`

```json
[
     {
        "id": "tools",
        "children":
        [{
            "caption": "SublimeREPL",
            "mnemonic": "R",
            "id": "SublimeREPL",
            "children":
            [
                {"command": "repl_open", 
                 "caption": "Julia",
                 "id": "repl_julia",
                 "mnemonic": "J",
                 "args": {
                    "type": "subprocess",
                    "encoding": "utf8",
                    "cmd": ["julia"],
                    "cwd": "$file_path",
                    "external_id": "julia",
                    "syntax": "Packages/Julia/Julia.tmLanguage"
                    }
                }
            ]   
        }]
    }
]

```

- `Default.sublime-commands`

```json
[
    {
        "caption": "SublimeREPL: Julia",
        "command": "run_existing_window_command", "args":
        {
            "id": "repl_julia",
            "file": "config/Julia/Main.sublime-menu"
        }
    }
]
```

I have Julia 1.7.2 installed by `conda` in my base environment, so `julia` is in my `PATH`. Hence I did not have to include absolute path of the binary.

**Comment by janxkoci** [comment]
I think I could add a simple prompt in a similar way to how it was done for Perl:

https://github.com/wuub/SublimeREPL/blob/d17e8649c0d0008a364158d671ac0c7d33d0c896/config/Perl/Main.sublime-menu#L18

The line references this file:
https://github.com/wuub/SublimeREPL/blob/master/config/Perl/re.pl
