### ISSUE TITLE
Node.js REPL Not Launch: throw new TypeError('stringToWrite must be a string')

### ISSUE THREAD

**Issue by littlee** [wuub/SublimeREPL#404]
I install SublimeREPL, and tried to launch Node REPL, but got error below:
```js
readline.js:220
    throw new TypeError('stringToWrite must be a string');
          ^
TypeError: stringToWrite must be a string
    at REPLServer._writeToOutput (readline.js:220:11)
    at REPLServer.Interface.prompt (readline.js:188:10)
    at REPLServer.displayPrompt (repl.js:400:8)
    at new REPLServer (repl.js:330:8)
    at Object.exports.start (repl.js:339:14)
    at C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\SublimeREPL\config\NodeJS\repl.js:5:20
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\SublimeREPL\config\NodeJS\repl.js:38:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)

***Repl Closed***
```
Operating System: Windows 7 64bit
Node Version: v0.12.0

How could I fix this problem, please?

**Comment by wppj** [comment]
I have encountered the same problem unfortunately... Weird...

**Comment by hmny** [comment]
same problem here,
using Win 8.1

**Comment by brosiusad** [comment]
Just installed SublimeREPL for the first time and this is what I'm seeing as well.

**Comment by mingqi** [comment]
I have same problem after replace node v.10 by iojs

**Comment by brakmic** [comment]
Same problem with v0.12.0

**Comment by GWesley** [comment]
Same problem node v0.12.2  & Mac OSX 10.10

Here is a way to build Node without REPL
1.Select Tools / BuildSystem / New BuildSystem
2.Enter name Node or whatever you like 
3.Add this to node.sublime-build file
{
  "cmd" : ["/usr/local/bin/node", "$file"],
  "selector" : "*.js"
}

This should work on mac and linux system, 
and type "which node" in terminal to find your own path, mine is "/usr/local/bin/node"

**Comment by littlee** [comment]
@GWesley 
Thanks for you suggestion.
BTW, do you know how to configure Sublime Text use this build system automatically when I press ctrl + B?

**Comment by mdszy** [comment]
I have also gotten this problem.

**Comment by pmp0x** [comment]
Same here

**Comment by janez87** [comment]
Same here using node 0.12.0 on OSX 10.10.2

**Comment by dimfeld** [comment]
Check out #364.  The fix for that worked for me on this issue as well.

**Comment by pascience** [comment]
Had this same error and https://github.com/wuub/SublimeREPL/issues/364 solved it indeed :+1:
