### ISSUE TITLE
SublimeREPL ipython text color changes

### ISSUE THREAD

**Issue by tblazina** [wuub/SublimeREPL#453]
When I opened an Ipython prompt in sublimeREPL today I found that whenever I type certain commands the text color in the REPL session changes to white after printing out commands with the form of: 

ESC[1;31 .... 

for example when I am using pandas and try to get the help information for a function this happens.

for example:   when I type: pd.Series?
it prints out:

[1;31mInit signature: [0m[0mpd[0m[1;33m.[0m[0mSeries[0m[1;33m([0m[0mself[0m[1;33m,[0m [0mdata[0m[1;33m=[0m[0mNone[0m[1;33m,[0m [0mindex[0m[1;33m=[0m[0mNone[0m[1;33m,[0m [0mdtype[0m[1;33m=[0m[0mNone[0m[1;33m,[0m [0mname[0m[1;33m=[0m[0mNone[0m[1;33m,[0m [0mcopy[0m[1;33m=[0m[0mFalse[0m[1;33m,[0m [0mfastpath[0m[1;33m=[0m[0mFalse[0m[1;33m)[0m[1;33m[0m[0m
[1;31mDocstring:[0m

with ESC before all of the '[' brackets .

Has anyone seen this before?

**Comment by tblazina** [comment]
So I've found that if I set either the 

c.InteractiveShell.colors variable equal to 'NoColor' 
or if i set 
c.InteractiveShell.color_info  equal to False

in my ipython_config.py setup, this removes the problem with the garbled output I described above however. It appears to have something to do with the pager. I've tried setting the:

c.TerminalInteractiveShell.pager= 'less'  to c.TerminalInteractiveShell.pager = '-r less' but this does not seem to have any effect when I have the c.InteractiveShell.colors set to eithe 'Linux' or anything else. Perhaps this is because i'm on Windows 7 and not on linux?

**Comment by tblazina** [comment]
I have found a work around that is not ideal but fixes the problem. 

In the SublimeREPL ipython prompt if I type %colors NoColor 
then this problem goes away. Apparently the 

cfg.InteractiveShell.colors = "NoColor"   in ipy_repl.py is somehow being over written?

**Comment by tblazina** [comment]
And finally I've solved the issue by simply adding:

c=get_config() to my ipython_config.py file and by uncommenting the 
c.InteractiveShell.colors = 'NoColor'  line.

Simple enough but that took a long time :+1:

**Comment by JacquotLeHaricot** [comment]
Hello tblazina,

After downgrading to IPython 2.4.1 I finally stabilized IPython in SublimeRepl to "only" your problem.
But which ipython_config.py are you talking about exactly ?

**Comment by tblazina** [comment]
Thanks for looking into this further! Sorry I was not more clear, I run the ipython which is installed with my Anaconda installation. And this was using Ipython 4.1.1. However,during my attempts to get around this problem I downgraded Ipython to 2.7 and the problem still was there. This is the ipython_config.py in  ...\Anaconda\Lib\site-packages\jupyter_core\tests\dotipython\profile_default

**Comment by JacquotLeHaricot** [comment]
Funny that this resolved your problem : I do not have Jupyter and all the ipython_config.py  files I found had the c=get_config() line..^^
Anyway thank to you it works with %colors=NoColor, and I'm sure further releases will deal with that kind of stuff.
