### ISSUE TITLE
Error trying to start *REPL*[ruby]

### ISSUE THREAD

**Issue by ajlee1000** [wuub/SublimeREPL#470]
It seems like this has been an issue since 2014
https://github.com/wuub/SublimeREPL/issues/336

And I am still getting the issue in 2016.

It would be nice to have a actual package fix for Ruby.

My specific issue is 

```
/Users/gilgameshskytrooper/Library/Application Support/Sublime Text 3/Packages/SublimeREPL/config/Ruby/pry_repl.rb:37:in `<main>': uninitialized constant Pry::InputCompleter (NameError)
Did you mean?  Pry::InputLock

***Repl Closed***
```

**Comment by ajlee1000** [comment]
worked through this 
https://github.com/wuub/SublimeREPL/pull/372/commits/95ffe15382336ef6720502752e71c290055cf7f8

**Comment by davidalejandroaguilar** [comment]
For some Package Control didn't include this change.
