### ISSUE TITLE
Maintained repo?

### ISSUE THREAD

**Issue by klonuo** [wuub/SublimeREPL#476]
Hi,

latest release seems old, and there are so many PR floating. I'd assume this package is not maintained anymore, but thought to ask if some of the forks is better to clone instead installing this through ST manager?

TIA

**Comment by klonuo** [comment]
Anyone willing to take this, so that we can focus there instead fencing the wall here?

**Comment by twirlimp** [comment]
Let me know if you found a solution.

**Comment by gacelita** [comment]
See #508
