### ISSUE TITLE
REPL R lines not evaluating

### ISSUE THREAD

**Issue by sadatnfs** [wuub/SublimeREPL#487]
I can send lines to the REPL R console (when REPL does decide to work which is quite random, I gotta find why that's the case) but everytime I do so, I have to switch to the console and press Enter to evaluate the lines sent. Is it possible to have this automated?

**Comment by fabeit** [comment]
Have you tried SendtoREPL package? it works for me, but I have another problem. The lines I send to REPL r don't appear in the R history

**Comment by ipstone** [comment]
I am using the ST3 Build 3126, with REPL R: the keyboard shortcut "C-, s" works fine for me to send selected codes to REPL R console for evaluating. I have used this on multiple machines (mostly windows), so I guess we may close this ticket.
