### ISSUE TITLE
Running infinite loop in python REPL

### ISSUE THREAD

**Issue by oro1989** [wuub/SublimeREPL#506]
running python code with infinite loop like this   :
```python
while True:  
    print("yes")   
```
or more complicated form causes sublime text 3 to stop working and give no output in the REPL

**Comment by oro1989** [comment]
this worked for me:
[https://github.com/wuub/SublimeREPL/issues/469](url)

**Comment by meichthys** [comment]
@oro1989 Glad that fix worked. Could you close the issue? There's effort being made to cleanup a lot of open issues, and it would help if you could mark this issue as resolved.
