### ISSUE TITLE
"cwd": "$file_path" line in Main.sublime-menu results in '/opt/sublime_text' as cwd in a run script

### ISSUE THREAD

**Issue by mazz3rr** [wuub/SublimeREPL#528]
I'm using Sublime Text 3 build 3126 on **Ubuntu Zesty**. I open a Python REPL with _CTRL+SHIFT+P >> SublimeREPL: Python_ and send a file to REPL with _CTRL+, , F_.

As long as I keep the

`"cwd": "$file_path"`

line in _Packages/SublimeREPL/config/Python/Main.sublime-menu_ I get `'/opt/sublime_text'` as a result of `os.getcwd()` in REPL. That is by no means a CWD for the file I'm sending to REPL (which is in my home folder). That means failing imports on modules located in the correct CWD (_ImportError: No module named modulename_) and not being able to open files located in that directory (_IOError: [Errno 2] No such file or directory: 'filename'_)

Changning the above line to:

`"cwd": "$folder"`

solves the problem. Now a call to `os.getcwd()` returns the path to the folder containing the file that was sent to SublimeREPL.

Granted as these are filepaths I'm not 100% sure the problem lies with SublimeREPL and not with the underlying system, but if the latter is not the case as `"cwd": "$file_path"` is the default setting it could mean breaking usability of SublimeREPL for vitually all Python users - a rather major issue.

Also I think a problem reported in a closed issue #355 could be caused by the same thing. Incidentally the solution given there by @wuub (adding a path by changing `_default_extend_env_ `had no discernible effect for me). There's also an open issue #410 that could relate to this.

I posted it also (as Q&A) on StackOverflow: https://stackoverflow.com/questions/45077749/why-sublimerepl-wont-import-a-python-module-or-read-a-file-in-cwd

**Comment by bscottm** [comment]
@tburly: Have you set up a SublimeText project file (`.sublime-project`) and added the `"cwd"` setting there? `Project > Save Project As ...` will get you started. `.sublime-project` files are a great way of localizing settings -- if that doesn't work as expected, then consider changing the issue's title to something like "`'cwd'`" not respected in SublimeText project settings".

**Comment by mazz3rr** [comment]
The problem was having a cursor in **a different pane** than the source file when opening REPL with <kbd>CTRL</kbd> <kbd>SHIFT</kbd> <kbd>P</kbd>. I learned that thx to [the great answer I got on SO](https://stackoverflow.com/a/45441695/4465708) and now it all looks trivial but back than I was driven mad and wanted to bash my head into a monitor. I guess it wouldn't hurt to make new users more aware of this behavior in some way.

I probably should close this issue now.
