### ISSUE TITLE
Cannot REPL Python 

### ISSUE THREAD

**Issue by Robert0812** [wuub/SublimeREPL#96]
I can compile Python script in sublime, but I cannot open any of the REPLs in sublimeREPL->python, and a messagebox appear everytime saying "WindowsError(2, The system cannot find the file specified.)". What's the problem?

**Comment by firs003** [comment]
Thanks a lot! This is really helpful.

**Comment by jhilmar1** [comment]
Thanks a lot!
NOTE: it's important the semicolon after {PATH}; ( I was using colon and does not work)

**Comment by dingyuanhong2006** [comment]
Hello, my environment is win10 + sublime text3 , and  Sublime does not support the input() function, so . we will do the following:  tools> SublimeREPL > python > python -  run current file ,   but  It gives you an error:    PermissionError(13, 'Access denied' ,None,5) .  why ？？？
